/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ChartCard: typeof import('./components/ChartCard.vue')['default']
    ConnectionSettings: typeof import('./components/ConnectionSettings.vue')['default']
    GroupEditView: typeof import('./components/GroupEditView.vue')['default']
    LineChart: typeof import('./components/LineChart.vue')['default']
    NTag: typeof import('naive-ui')['NTag']
    PerformanceMonitor: typeof import('./components/PerformanceMonitor.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TagGroupEditor: typeof import('./components/TagGroupEditor.vue')['default']
    TagGroupTree: typeof import('./components/TagGroupTree.vue')['default']
    TagSearchModal: typeof import('./components/TagSearchModal.vue')['default']
    TagSearchSelect: typeof import('./components/TagSearchSelect.vue')['default']
    TimeRangeSelector: typeof import('./components/TimeRangeSelector.vue')['default']
  }
}
