/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ConnectionSettings: typeof import('./components/ConnectionSettings.vue')['default']
    DataTable: typeof import('./components/DataTable.vue')['default']
    LineChart: typeof import('./components/LineChart.vue')['default']
    NH2: typeof import('naive-ui')['NH2']
    NTabPane: typeof import('naive-ui')['NTabPane']
    NTabs: typeof import('naive-ui')['NTabs']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TagSelector: typeof import('./components/TagSelector.vue')['default']
    TimeRangeSelector: typeof import('./components/TimeRangeSelector.vue')['default']
  }
}
